---
title: "Hadoop/PySpark notes"
output:
  html_document:
    theme: "cerulean" 
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  pdf_document:
    toc: true
---

## Introduction
I wanted to figure out how to do a few things in PySpark. I have a single node Hadoop/PySpark "cluster" running on a raspberry Pi, so I'm not going to be crunching a tonne of data. I wanted to try doing the following:

  * Interact with with an RDBMS using spark SQL
  * Run a MapReduce task on some data
  * do something with MLlib


## SQL stuff

Query a database through spark. Have a small database containing information on things related to 4th edition Dungeons and Dragons. The following script quickly queries the db and prints some info on fighter powers.

```{python, eval=FALSE}
#!/usr/local/spark/spark-2.2.0-bin-hadoop2.7/bin/pyspark

# this shebang doesn't work, call ${SPARK_HOME}/bin/spark-submit file.py

# setup Spark configuration
from pyspark import SparkConf, SparkContext
conf = SparkConf()
conf.setMaster("spark://ravage:7077")
conf.setAppName("My application")
conf.set("spark.executor.memory", "512m")
conf.set("sparkHome","/usr/local/spark/spark-2.2.0-bin-hadoop2.7")

# spark sql stuff
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("pyspark sqlite test") \
    .config(conf=conf) \
    .getOrCreate()

# use the jdbc sqlite driver to read our db
sqliteDF = spark.read.format('jdbc').options(
    # url='jdbc:sqlite:hdfs://localhost:54310/user/hduser/cleanedDB.db',
    url='jdbc:sqlite:/home/hduser/cleanedDB.db',
    driver='org.sqlite.JDBC',
    dbtable='Powers').load()

# query

sqliteDF.select(sqliteDF['classname'],sqliteDF['name'],sqliteDF['level']).filter(sqliteDF['classname'] == 'Fighter').show()

```

This work, and produces the following output:

```
+---------+--------------------+-----+
|classname|                name|level|
+---------+--------------------+-----+
|  Fighter|      Dance of Steel|    3|
|  Fighter|         Shield Slam|    3|
|  Fighter|       Rain of Blows|    3|
|  Fighter|         Shield Bash|    1|
|  Fighter|       Sweeping Blow|    3|
|  Fighter|       Battering Ram|   17|
|  Fighter|     Griffon's Wrath|    7|
|  Fighter|       Crushing Blow|    3|
|  Fighter|Armor-Piercing Th...|    3|
|  Fighter|         Not So Fast|    7|
|  Fighter|             Trip Up|    7|
|  Fighter|              Cleave|    1|
|  Fighter|      Reaping Strike|    1|
|  Fighter|        Tide of Iron|    1|
|  Fighter|      Spinning Sweep|    1|
|  Fighter|Steel Serpent Strike|    1|
|  Fighter|      Passing Attack|    1|
|  Fighter|        Sudden Surge|    7|
|  Fighter|        Iron Bulwark|    7|
|  Fighter|       Anvil of Doom|   13|
+---------+--------------------+-----+
```

## MapReduce

#### Power Descriptions
There are a lot of different powers for each combination of class and level. The details of each power are recorded in the descriptionRaw column, which contains html. The description for "Come and Get it" is given below:

```
<div id="detail"> 
<h1 class="encounterpower"> Come and Get It</h1>
<p class="flavor"><i>You brandish your weapon and call out to your foes, luring them close through their overconfidence, and then deliver a spinning strike against them all.</i></p>
<p class="powerstat"><b>Encounter</b>  <b>Martial</b>, <b>Weapon</b><br/>
<b>Standard Action</b> <b>Close</b> burst 3</p>
<p class="powerstat"><b>Target</b>: Each enemy you can see in the burst</p>
<p class="powerstat"><b>Attack</b>: Strength vs. Will</p>
<p class="flavor"><b>Hit</b>: You pull the target up to 2 squares, but only if it can end the pull adjacent to you. If the target is adjacent to you after the pull, it takes 1[W] damage.</p><br/>

<p class="publishedIn">Published in <a href="http://www.wizards.com/default.asp?x=products/dndacc/217367200" target="_new">Player's Handbook</a>, page(s) 80, <a href="http://www.wizards.com/dnd" target="_new">Class Compendium</a>.</p> </div>
```

Will want to use an html parser to extract the keyword information. Each power has keywords that indicate its properties, these are contained in the ```<p>``` block with class "powerstat" following the flavortext. The power above has the keywords, martial, weapon, standard action, and close burst 3. 

#### Extracting Keywords
The script below cleans and parses the initial html for our test power, and prints the keywords 


```{python, eval=FALSE}
#!/usr/bin/env python

import re

from bs4 import BeautifulSoup
# our cleandb has the html pretty tidy, really just want to strip out the <b>, <i>, and <br/> tags
def clean(input):
    output = input
    output = re.sub(r'<br/>',' ',output)
    output = re.sub(r'</?[bi]>','',output)
    return(output)

# load our "test" power
filename = 'testPower.txt'
content =  open(filename,'r').read()
content = clean(content)
# parse cleaned html
html = BeautifulSoup(content,'html.parser')
# first p element with class "powerstat"
keywordsTag = html.find_all(name='p',class_='powerstat')[0]

# # clean up the keywords a bit
keywords = re.sub(',','',keywordsTag.text.lower())
keywords = re.sub('^ | $ ','',keywords)
keywords = re.sub('\s+',' ',keywords)

print(keywords)

```
Which yields:
```
encounter martial weapon standard action close burst 3
```

We could turn the above code into a function and apply that to the descriptionRaw column in the pyspark dataframe. Instead, we'll dump out the each power's class, level, and keywords to a (several?) text files, and use mapReduce functionality to aggregate the keyword information by class and level.

#### Dumping Keywords

The following script dumps all the keywords out to a text file, using the python DB-API for sqlite3. I'm interested in keywords by class and level, so construct a key from this information.

```{python, eval=FALSE}
#!/usr/bin/env python

import sqlite3
import re,sys
from bs4 import BeautifulSoup

# get the keywords from the html
def getKeywords(descRaw):
    content = re.sub(r'<br/>',' ',descRaw)
    content = re.sub(r'</?[bi]>','',content)
    html = BeautifulSoup(content,'html.parser')
    keywordsTag = html.find_all(name='p',class_='powerstat')[0]
    keywords = re.sub(',','',keywordsTag.text.lower())
    keywords = re.sub('^ | $ ','',keywords)
    keywords = re.sub('\s+',' ',keywords)
    return(keywords)

# filenames
cleanDBname = './cleanedDB.db'
outfileName = './powerKeywords.txt'

# connect to DB
cleanConn = sqlite3.connect(cleanDBname)
cleanConn.row_factory = sqlite3.Row
cleancur = cleanConn.cursor()

# query
cleanquery= 'SELECT id,classname,level,descriptionRaw FROM Powers'
cleancur.execute(cleanquery)

# hold the output here, then write it
# db is small, so memory won't be an issue, otherwise we could write each line as we retreive its row
lines = []

# loop over query results (rows)
for therow in cleancur:
    keywords = getKeywords(therow['descriptionRaw'].encode('utf-8'))
    # print('id = {id:5}, name = {name}, keywords = {keywords}'.format(id=therow['id'],name=therow['name'],keywords=keywords))
    
    # Some powers don't have a valid level associated with them
    # (and the db contains garbage level values, HASHXX - perl related?)
    try:
        levelint = int(therow['level'])
    except ValueError:
        continue
    try:
        lines.append(
            '{classname}_{level} {keywords}\n'.format(
                classname=re.sub(r' ','_',therow['classname'].encode('utf-8')),
                level=therow['level'],
                keywords=keywords.encode('utf-8')
                )
            )
    except UnicodeEncodeError:
        print('UnicodeError : powerid = {id}\n'.format(id=therow['id']))
        sys.exit()
cleancur.close()


try:
    with open(outfileName,'w') as outfile:
        for line in lines:
            outfile.write(line)
except IOError:
    print('Error, could not open {outfilename} for writing'.format(outfilename=outfileName))
    sys.exit()

```

This produces the following:

```
Warlord_6 daily martial stance minor action personal 
Paladin_10 encounter divine minor action ranged 5
Wizard_6 daily arcane move action personal 
Warlock_13 encounter arcane implement thunder standard action ranged 10
Wizard_15 daily arcane evocation fire implement poison standard action close blast 5
Ranger_16 daily martial stance minor action personal 
Druid_10 daily primal zone minor action close burst 3
Ranger_15 daily martial weapon standard action melee weapon
Cleric_9 daily conjuration divine implement standard action area wall 5 within 10 squares
...
```

There are 9409 powers in the database. Of these, 646 do not have a well defined level (racial powers, class features, wizard cantrips, etc), leaving 8773 powers for which keywords were extracted.

### MapReduce

Now have all the keyword info in a text file. Will copy this into hadoops dfs then feed it to spark and do some mapreducing

